=== Zoom-Apps/backbrace/schema/tablemeta.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "https://labs.zoomapps.com.au/JumpstartCDN/schemas/tableMeta",
    "title": "Table meta data.",
    "type": "object",
    "properties": {
        "name": {
            "description": "Name of the table.",
            "type": "string"
        },
        "controller": {
            "description": "Table controller.",
            "type": "string"
        },
        "data": {
            "description": "Table data (if from a file)",
            "type": "string"
        },
        "columns": {
            "description": "Table columns.",
            "type": "array",
            "items": {
                "$ref": "#/definitions/tableColumnMeta"
            }
        }
    },
    "required": [
        "columns"
    ],
    "definitions": {
        "tableColumnMeta": {
            "description": "Table column meta data.",
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the column.",
                    "type": "string"
                },
                "caption": {
                    "description": "Caption of the column.",
                    "type": "string"
                },
                "type": {
                    "description": "Data type for the column.",
                    "type": "string",
                    "$ref": "datatypes.json"
                }
            },
            "required": [
                "name",
                "type"
            ]
        }
    }
}

=== Zoom-Apps/backbrace/sample/meta/tables/employee.json
{
    "name": "Employee",
    "controller": "tables/employee.js",
    "data": "./data/employee.json",
    "columns": [
        {
            "name": "ID",
            "type": "Integer"
        },
        {
            "name": "firstName",
            "caption": "First Name",
            "type": "Text"
        },
        {
            "name": "lastName",
            "caption": "Last Name",
            "type": "Text"
        },
        {
            "name": "dob",
            "caption": "Date of Birth",
            "type": "Date"
        },
        {
            "name": "salary",
            "caption": "Salary",
            "type": "Decimal"
        }
    ]
}
